# Generated by Django 6.0.2 on 2026-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='user',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='user_id',
            field=models.CharField(default='legacy_user', max_length=255),
            preserve_default=False,
        ),
    ]
