# Generated by Django 6.0.2 on 2026-02-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_resumeanalysis_user_resumeanalysis_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeAnalysis',
        ),
    ]
